In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(context='talk', style='ticks',
        color_codes=True, rc={'legend.frameon': False})

%matplotlib inline
import matplotlib
matplotlib.rcParams['figure.dpi'] = 300
plt.rcParams["font.family"] = 'Arial'
plt.rcParams.update({'font.size': 24})
plt.rcParams['svg.fonttype'] = 'none'

In [3]:
mordred_df = pd.read_csv('../data/processed/aqsol_db_mordred_descs.csv')
mordred_df

/tmp/ipykernel_1527244/1811763504.py:1: DtypeWarning: Columns (114,115,116,117,118,119,120,121,122,213,321,322,323,324,325,326,327,328,329,429,861,869) have mixed types. Specify dtype option on import or set low_memory=False.
  mordred_df = pd.read_csv('../data/processed/aqsol_db_mordred_descs.csv')

,ID,Name,InChI,InChIKey,SMILES,Solubility,Prediction,ABC,ABCGG,nAcid,...,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb1,mZagreb2
0,A-1,"1,2-dichlorobenzene",InChI=1S/C6H4Cl2/c7-5-3-1-2-4-6(5)8/h1-4H,RFFLAFLAYFXFSW-UHFFFAOYSA-N,Clc1ccccc1Cl,-3.177212,-3.05,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,8.555837,35.908899,145.969005,12.164084,60,8,36.0,39.0,3.2222222222222223,1.861111
1,A-2,"1,2-dichlorobenzene",InChI=1S/C6H4Cl2/c7-5-3-1-2-4-6(5)8/h1-4H,RFFLAFLAYFXFSW-UHFFFAOYSA-N,Clc1ccccc1Cl,-3.180557,-3.05,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,8.555837,35.908899,145.969005,12.164084,60,8,36.0,39.0,3.2222222222222223,1.861111
2,A-3,"N,N,N-trimethyloctadecan-1-aminium bromide",InChI=1S/C21H46N.BrH/c1-5-6-7-8-9-10-11-12-13-...,SZEMGTQCPRNXEG-UHFFFAOYSA-M,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,-7.50,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,1,...,8.878079,54.228660,391.281363,5.670744,2200001716,19,88.0,86.0,divide by zero encountered in power (mZagreb1),5.375000
3,A-4,Benzo[cd]indol-2(1H)-one,InChI=1S/C11H7NO/c13-11-8-5-1-3-7-4-2-6-9(12-1...,GPYLCFQEKPUWLD-UHFFFAOYSA-N,O=C1Nc2cccc3cccc1c23,-3.254767,-2.85,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,9.744550,59.616539,169.052764,8.452638,207,21,74.0,91.0,3.305555555555556,2.777778
4,A-5,4-chlorobenzaldehyde,InChI=1S/C7H5ClO/c8-7-3-1-6(5-9)2-4-7/h1-5H,AVPYQKSLYISFPO-UHFFFAOYSA-N,Clc1ccc(C=O)cc1,-2.177078,-2.27,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,8.590258,37.289972,140.002892,10.000207,90,9,40.0,43.0,3.4722222222222223,2.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6105,A-6106,"bis(2-ethylhexyl) 3,4,5,6-tetrabromophthalate",InChI=1S/C24H34Br4O4/c1-5-9-11-15(7-3)13-31-23...,UUEDINPOVKWVAZ-UHFFFAOYSA-N,CCCCC(CC)COC(=O)c1c(Br)c(Br)c(Br)c(Br)c1C(=O)O...,-10.149926,-7.46,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,10.186597,67.268242,701.919058,10.635137,3126,51,148.0,170.0,14.11111111111111,7.722222
6106,A-6107,niobium,InChI=1S/Nb,GUCVJGMIXFAOAE-UHFFFAOYSA-N,[Nb],-9.314831,NaN,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,0.000000,1.000000,92.906378,92.906378,0,0,0.0,0.0,divide by zero encountered in power (mZagreb1),0.000000
6107,A-6108,1-(chloromethyl)-4-[4-(chloromethyl)phenyl]ben...,InChI=1S/C14H12Cl2/c15-9-11-1-5-13(6-2-11)14-7...,INZDTEICWPZYJM-UHFFFAOYSA-N,ClCc1ccc(cc1)c2ccc(CCl)cc2,-10.098914,-6.31,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,9.453679,47.962977,250.031606,8.929700,480,22,78.0,89.0,4.944444444444445,3.777778
6108,A-6109,N-methyl-N-phenyl{[methyl(phenyl)carbamothioyl...,InChI=1S/C16H16N2S4/c1-17(13-9-5-3-6-10-13)15(...,RDQQCSOIXMZZQR-UHFFFAOYSA-N,CN(C(=S)SSC(=S)N(C)c1ccccc1)c2ccccc2,-10.561800,-5.59,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,9.712751,55.398300,364.019633,9.579464,1203,31,106.0,120.0,7.666666666666666,5.027778
6109,A-6110,"2-(2H-1,2,3-benzotriazol-2-yl)-6-{[3-(2H-1,2,3...","InChI=1S/C41H50N6O2/c1-38(2,3)24-40(7,8)28-20-...",FQUNFJULCYSSOP-UHFFFAOYSA-N,CC(C)(C)CC(C)(C)c1cc(Cc2cc(cc(n3nc4ccccc4n3)c2...,-11.119844,-6.16,module 'numpy' has no attribute 'float'.\n`np....,module 'numpy' has no attribute 'float'.\n`np....,0,...,11.029861,103.843842,658.399525,6.650500,8642,84,278.0,330.0,18.555555555555557,9.888889

In [4]:
desc_df = mordred_df.select_dtypes(['number'])
desc_df['ID'] = mordred_df['ID']
#desc_df['Name'] = mordred_df['Name']
#desc_df['InChI'] = mordred_df['InChI']
#desc_df['SMILES'] = mordred_df['SMILES']
desc_df = desc_df.set_index('ID')
desc_df = desc_df.dropna(axis=0)
desc_df.to_csv('../data/processed/20250501_aqsol_db_mordred_descs_cleaned.csv')

In [6]:
desc_df = pd.read_csv('../data/processed/20250501_aqsol_db_mordred_descs_cleaned.csv')
desc_df

,ID,Solubility,Prediction,nAcid,nBase,nAromAtom,nAromBond,nAtom,nHeavyAtom,nSpiro,...,SRW09,SRW10,TSRW10,MW,AMW,WPath,WPol,Zagreb1,Zagreb2,mZagreb2
0,A-1,-3.177212,-3.05,0,0,6,6,12,8,0,...,0.000000,8.555837,35.908899,145.969005,12.164084,60,8,36.0,39.0,1.861111
1,A-2,-3.180557,-3.05,0,0,6,6,12,8,0,...,0.000000,8.555837,35.908899,145.969005,12.164084,60,8,36.0,39.0,1.861111
2,A-3,-3.616127,-7.50,1,1,0,0,69,23,0,...,0.000000,8.878079,54.228660,391.281363,5.670744,2200001716,19,88.0,86.0,5.375000
3,A-4,-3.254767,-2.85,0,0,10,11,20,13,0,...,7.050123,9.744550,59.616539,169.052764,8.452638,207,21,74.0,91.0,2.777778
4,A-5,-2.177078,-2.27,0,0,6,6,14,9,0,...,0.000000,8.590258,37.289972,140.002892,10.000207,90,9,40.0,43.0,2.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5673,A-6105,-10.234717,-7.54,0,3,0,0,160,61,0,...,7.678326,10.292315,114.536340,857.769707,5.361061,31454,72,266.0,286.0,14.833333
5674,A-6106,-10.149926,-7.46,0,0,6,6,66,32,0,...,0.000000,10.186597,67.268242,701.919058,10.635137,3126,51,148.0,170.0,7.722222
5675,A-6108,-10.098914,-6.31,0,0,12,12,28,16,0,...,0.000000,9.453679,47.962977,250.031606,8.929700,480,22,78.0,89.0,3.777778
5676,A-6109,-10.561800,-5.59,0,0,12,12,38,22,0,...,0.000000,9.712751,55.398300,364.019633,9.579464,1203,31,106.0,120.0,5.027778
5677,A-6110,-11.119844,-6.16,0,0,30,32,99,49,0,...,7.535297,11.029861,103.843842,658.399525,6.650500,8642,84,278.0,330.0,9.888889

In [10]:
data_row = desc_df.loc[0].tolist()
data_row.pop(0)

'A-1'

In [11]:
data_row

[-3.1772123861,
 -3.05,
 0,
 0,
 6,
 6,
 12,
 8,
 0,
 0,
 2,
 4,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 69.20987654320987,
 73.22222222222223,
 76.88888888888889,
 42.938271604938265,
 4.666666666666667,
 0.0,
 0.0,
 0.0,
 0.0,
 40.0,
 47.0,
 60.0,
 50.0,
 20.0,
 3.0,
 0.0,
 0.0,
 0.0,
 798.0,
 444.0,
 672.0,
 890.0,
 298.0,
 35.0,
 0.0,
 0.0,
 0.0,
 3383.0539819999995,
 1765.592978,
 2665.60123,
 3564.0267590000003,
 1044.97478,
 72.483264,
 0.0,
 0.0,
 0.0,
 3673.378305045882,
 3924.039691696683,
 5306.977972897386,
 4883.971687468753,
 1945.7502262895125,
 281.40597254440405,
 0.0,
 0.0,
 0.0,
 78.34620000000001,
 77.571,
 116.127,
 135.02910000000003,
 76.04400000000001,
 18.744000000000003,
 0.0,
 0.0,
 0.0,
 28.016651619396,
 28.468777239999994,
 40.20415448,
 40.830910674547,
 18.439038009698,
 3.351830384849,
 0.0,
 0.0,
 0.0,
 1836.7556002707963,
 1665.2951355696005,
 2569.8241345992,
 3265.032605019028,
 1979.7226126784583,
 537.596806824429,
 0.0,
 0.0,
 0.0,
 5.767489711934156,
 3.333333333333333,
 66.5,
 281.92116516666664,
 306.1148587538235,
 6.528850000000001,
 2.3347209682829995,
 153.06296668923304,
 30.48971193415637,
 1.370370370370366,
 -14.323045267489713,
 -8.25617283950617,
 -0.9218106995884728,
 6.885802469135804,
 0.0,
 0.0,
 0.0,
 6.666666666666668,
 0.3333333333333327,
 -3.333333333333334,
 -1.6666666666666663,
 4.440892098500626e-16,
 1.3333333333333337,
 0.0,
 0.0,
 0.0,
 341.66666666666663,
 1.1102230246251563e-15,
 -0.1666666666666648,
 85.24999999999999,
 -170.66666666666663,
 -85.25,
 0.0,
 0.0,
 0.0,
 1582.3529816666671,
 8.437694987151191e-15,
 -0.3422481666666632,
 395.24599725,
 -790.8342426666668,
 -395.2459972500001,
 0.0,
 0.0,
 0.0,
 643.5725211426012,
 -6.927791673660978e-14,
 -131.96461075093572,
 28.928519534714685,
 -189.82164982036488,
 -28.928519534714624,
 0.0,
 0.0,
 0.0,
 1.2314999999999996,
 5.377642775528102e-17,
 -0.0013499999999999,
 0.3065249999999999,
 -0.6144000000000001,
 -0.306525,
 0.0,
 0.0,
 0.0,
 3.799478852930666,
 6.800116025829084e-16,
 -0.3732091432326658,
 0.5766605699999998,
 -1.5265302832326677,
 -0.5766605700000006,
 0.0,
 0.0,
 0.0,
 14.114084466443984,
 7.271960811294775e-15,
 -6.791758872575986,
 -3.263237755965,
 -0.2652833606460075,
 3.263237755964992,
 0.0,
 0.0,
 0.0,
 2.5408093278463646,
 0.5555555555555557,
 28.47222222222221,
 131.86274847222228,
 53.6310434285501,
 0.1026249999999999,
 0.3166232377442222,
 1.1761737055369987,
 2.2794002709583667,
 162.63833891467198,
 12,
 8,
 6,
 0,
 0,
 6,
 6,
 9,
 3,
 0,
 0,
 0,
 6,
 0,
 0,
 0,
 0,
 0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0833333333333333,
 0.1666666666666666,
 0.0,
 0.0,
 0.0,
 0.0277777777777777,
 0.0629940788348712,
 0.4714045207910317,
 0.0,
 0.1666666666666666,
 0.0,
 0.3273268353539885,
 0.0,
 0.1071428571428571,
 0.0,
 1.1380711874576983,
 1.040440114519881,
 1.1380711874576983,
 0.7491182174882725,
 0.5416125496397028,
 0.4994121449921814,
 3.804530452640311,
 3.2390248187615978,
 2.5403364137778537,
 1.501661279183041,
 1.0243773949903288,
 0.3333333333333333,
 0.0833333333333333,
 2.961243688217307,
 2.228509027609715,
 1.5802810806327734,
 0.7107613275815924,
 0.4017637694544053,
 0.1259881576697424,
 0.0357142857142857,
 12.333333333333332,
 12.238614603280327,
 9.265367392631797,
 11.929411764705884,
 10.2078874251497,
 13.133826985071446,
 1.0277777777777777,
 1.019884550273361,
 0.7721139493859829,
 0.9941176470588236,
 0.8506572854291417,
 1.0944855820892871,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 4,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 7.190679012345679,
 0.0,
 0.0,
 0.0,
 0.0,
 1.2114197530864206,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0,
 0,
 0.0,
 0.0,
 0.0,
 0,
 0.0,
 0.0,
 0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 11.153456790123457,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.0,
 0,
 0.0,
 0,
 0,
 0,
 0.0,
 0.0,
 0,
 0,
 0,
 0.0,
 54,
 8.02,
 0.5,
 0,
 0,
 1.4591479170272448,
 1.918295834054489,
 2.2516291673878226,
 2.584962500721156,
 2.584962500721156,
 2.584962500721156,
 17.509775004326936,
 23.01955000865388,
 27.01955000865388,
 31.01955000865388,
 31.01955000865388,
 31.01955000865388,
 2.125814583693911,
 1.6666666666666667,
 1.3333333333333337,
 1.0,
 1.0,
 1.0,
 21.81215998992017,
 27.3269856213344,
 31.33065228800107,
 31.666652288001067,
 31.666652288001067,
 31.666652288001067,
 34.76140417171476,
 34.61102917892632,
 32.27117917604169,
 31.881204175560924,
 31.881204175560924,
 31.881204175560924,
 -3.002181541955481,
 96.12,
 58.03793557326031,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 35.33461391738825,
 12.13273413692322,
 0.0,
 10.045266627482652,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 34.31073490132909,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 24.26546827384644,
 10.045266627482652,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 10.045266627482652,
 0.0,
 0.0,
 12.13273413692322,
 12.13273413692322,
 0.0,
 23.20187978046503,
 0.0,
 0.0,
 0.0,
 1.2114197530864206,
 0.0,
 0.0,
 7.190679012345679,
 0.0,
 0.0,
 0.0,
 10,
 11,
 10,
 10,
 4,
 1,
 0,
 0,
 0,
 62,
 2.4849066497880004,
 3.0204248861443626,
 3.457892725338701,
 3.803880846808443,
 4.201890188785264,
 3.446011397451948,
 2.1510351948668447,
 0.0,
 0.0,
 0.0,
 5.384064924421284,
 17.047171999999996,
 5.032827999999999,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2.9934000000000003,
 36.46200000000001,
 0.0,
 0.0,
 1.5,
 1.1111111111111116,
 0.375,
 0.2222222222222222,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.1875,
 0.1111111111111111,
 0.046875,
 0.1111111111111111,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.4565972222222222,
 4,
 3,
 8.0,
 3.610917912644224,
 4.3694478524670215,
 5.153291594497779,
 5.932245187448011,
 6.717804695023691,
 7.501634457883413,
 8.287276755814599,
 9.072341873818893,
 9.857914707241372,
 76.50287503683901,
 2.833213344056216,
 0.0,
 4.04305126783455,
 0.0,
 5.476463551931511,
 0.0,
 7.00033446027523,
 0.0,
 8.555836815008442,
 35.90889943910595,
 145.969005488,
 12.164083790666666,
 60,
 8,
 36.0,
 39.0,
 1.8611111111111112]